package cn.edu.upc.bdl.model;

public class Cp extends CpKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.qty
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.qty
     *
     * @return the value of cp.qty
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.qty
     *
     * @param qty the value for cp.qty
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}