package cn.edu.upc.bdl.model;

import java.math.BigDecimal;

public class Cp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.cpno
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    private Integer cpno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.id
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.no
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.qty
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    private Integer qty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.date
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.cost
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    private BigDecimal cost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.cpno
     *
     * @return the value of cp.cpno
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public Integer getCpno() {
        return cpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.cpno
     *
     * @param cpno the value for cp.cpno
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public void setCpno(Integer cpno) {
        this.cpno = cpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.id
     *
     * @return the value of cp.id
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.id
     *
     * @param id the value for cp.id
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.no
     *
     * @return the value of cp.no
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.no
     *
     * @param no the value for cp.no
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.qty
     *
     * @return the value of cp.qty
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.qty
     *
     * @param qty the value for cp.qty
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.date
     *
     * @return the value of cp.date
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.date
     *
     * @param date the value for cp.date
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.cost
     *
     * @return the value of cp.cost
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.cost
     *
     * @param cost the value for cp.cost
     *
     * @mbg.generated Sat Jul 11 11:19:45 CST 2020
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
}