package cn.edu.upc.bdl.model;

public class CpKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.id
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp.no
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private Integer no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.id
     *
     * @return the value of cp.id
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.id
     *
     * @param id the value for cp.id
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp.no
     *
     * @return the value of cp.no
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp.no
     *
     * @param no the value for cp.no
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setNo(Integer no) {
        this.no = no;
    }
}