package cn.edu.upc.bdl.model;

public class Customers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.id
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.username
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.password
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.score
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.id
     *
     * @return the value of customers.id
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.id
     *
     * @param id the value for customers.id
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.username
     *
     * @return the value of customers.username
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.username
     *
     * @param username the value for customers.username
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.password
     *
     * @return the value of customers.password
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.password
     *
     * @param password the value for customers.password
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.score
     *
     * @return the value of customers.score
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.score
     *
     * @param score the value for customers.score
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}