package cn.edu.upc.bdl.model;

import java.math.BigDecimal;

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.no
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.name
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.resever
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    private Integer resever;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.no
     *
     * @return the value of products.no
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.no
     *
     * @param no the value for products.no
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.name
     *
     * @return the value of products.name
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.name
     *
     * @param name the value for products.name
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.resever
     *
     * @return the value of products.resever
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public Integer getResever() {
        return resever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.resever
     *
     * @param resever the value for products.resever
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    public void setResever(Integer resever) {
        this.resever = resever;
    }
}