package cn.edu.upc.bdl.dao;

import cn.edu.upc.bdl.model.Cp;
import cn.edu.upc.bdl.model.CpKey;

public interface CpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int deleteByPrimaryKey(CpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insert(Cp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insertSelective(Cp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    Cp selectByPrimaryKey(CpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKeySelective(Cp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKey(Cp record);
}