package cn.edu.upc.bdl.dao;

import cn.edu.upc.bdl.model.Customers;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomersMapper {

    List<Customers> selectAll();
    List<Customers> selectByUsername(String username);
    List<Customers> selectPasswordByID(Integer id);
    int updatePasswordById(@Param("id")int id, @Param("password")String password);//传类型不同的多值方法之一
    int updateScoreById(@Param("id")int id, @Param("score")int score);
    int delete(int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insertSelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    Customers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKeySelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKey(Customers record);
}