package cn.edu.upc.bdl.dao;

import cn.edu.upc.bdl.model.Customers;

public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insertSelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    Customers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKeySelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKey(Customers record);
}