package cn.edu.upc.bdl.dao;

import cn.edu.upc.bdl.model.Products;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductsMapper {

    List<Products> selectAll();
    List<Products> selectByName(String name);
    int updateReserve(@Param("no")int no, @Param("reserve")int reserve);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int deleteByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insert(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int insertSelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    Products selectByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKeySelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Jul 06 16:30:43 CST 2020
     */
    int updateByPrimaryKey(Products record);
}